### ISSUE TITLE
JS error in new site on Edge Chromium on Windows 10 (83.0.478.61)

### ISSUE THREAD

**Issue by nriley** [samuelclay/NewsBlur#1508]
Story list doesn't appear.  Works fine in Google Chrome (91.0.4472.124 ) on the same computer. old.newsblur.com works too.

```
common.js?1625257681:2177 Uncaught TypeError: d.replaceAll is not a function
    at e.content_preview (common.js?1625257681:2177)
    at e.show_content_preview (common.js?1625257681:2594)
    at e.render (common.js?1625257681:2588)
    at common.js?1625257681:2624
    at Array.map (<anonymous>)
    at Function.t.map.t.collect (common.js?1625257681:1484)
    at e.q.<computed> [as map] (common.js?1625257681:1549)
    at e.render (common.js?1625257681:2623)
    at v (common.js?1625257681:1531)
    at e.trigger (common.js?1625257681:1530)
```

**Comment by samuelclay** [comment]
What does the JS error look like on staging.newsblur.com (where I have DEBUG_ASSETS turned on)?

**Comment by nriley** [comment]
```Uncaught TypeError: content.replaceAll is not a function
    at child.content_preview (stories.js:54)
    at child.show_content_preview (story_title_view.js:217)
    at child.render (story_title_view.js:38)
    at story_titles_view.js:45
    at Array.map (<anonymous>)
    at Function._.map._.collect (underscore-1.4.3.js:97)
    at child.Collection.<computed> [as map] (backbone-1.0.0.js:953)
    at child.render (story_titles_view.js:38)
    at triggerEvents (backbone-1.0.0.js:205)
    at child.trigger (backbone-1.0.0.js:146)```

**Comment by samuelclay** [comment]
Fixed in 889caf82a and cb1f16881.

**Comment by nriley** [comment]
Working now. Thanks!
